<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="EndJinx.Tests/**/*.cs" />
    <Compile Remove="src/**/*.cs" />
    <EmbeddedResource Remove="EndJinx.Tests/**/*.resx" />
    <None Remove="EndJinx.Tests/**/*" />
  </ItemGroup>
</Project>
